"""Reference disease catalog used for model training and clinical guidance."""

from dataclasses import dataclass

from mediai.core.enums import DiseaseSeverity


@dataclass(frozen=True, slots=True)
class DiseaseProfile:
    code: str
    name: str
    severity: DiseaseSeverity
    specialty: str
    description: str
    triage_guidance: str
    recommended_labs: tuple[str, ...]
    recommended_specialists: tuple[str, ...]
    lifestyle_advice: tuple[str, ...]
    symptom_profile: dict[str, float]


CLINICAL_FEATURES: tuple[str, ...] = (
    "age",
    "fever_celsius",
    "cough_severity",
    "sore_throat",
    "shortness_of_breath",
    "chest_pain",
    "headache",
    "fatigue",
    "nausea",
    "vomiting",
    "diarrhea",
    "abdominal_pain",
    "rash",
    "urinary_burning",
    "joint_pain",
    "loss_of_taste_smell",
    "oxygen_saturation",
    "systolic_bp",
    "diastolic_bp",
    "heart_rate",
    "respiratory_rate",
    "glucose_mg_dl",
    "wbc_count",
    "platelets_count",
    "travel_exposure",
    "contact_exposure",
    "chronic_conditions_count",
    "symptom_duration_days",
    "weight_loss",
    "neck_stiffness",
    "photophobia",
)


DISEASE_PROFILES: tuple[DiseaseProfile, ...] = (
    DiseaseProfile(
        code="influenza",
        name="Influenza",
        severity=DiseaseSeverity.MODERATE,
        specialty="Infectious Diseases",
        description="Acute viral respiratory infection with systemic symptoms and fever.",
        triage_guidance="Supportive care is typical unless respiratory compromise or high-risk features are present.",
        recommended_labs=("Influenza PCR", "CBC", "CRP"),
        recommended_specialists=("Primary Care", "Infectious Diseases"),
        lifestyle_advice=("Hydrate well", "Rest", "Monitor temperature"),
        symptom_profile={
            "fever_celsius": 38.7,
            "cough_severity": 2,
            "sore_throat": 1,
            "shortness_of_breath": 0,
            "chest_pain": 0,
            "headache": 1,
            "fatigue": 2,
            "nausea": 0,
            "vomiting": 0,
            "diarrhea": 0,
            "abdominal_pain": 0,
            "rash": 0,
            "urinary_burning": 0,
            "joint_pain": 1,
            "loss_of_taste_smell": 0,
            "oxygen_saturation": 97,
            "systolic_bp": 122,
            "diastolic_bp": 78,
            "heart_rate": 94,
            "respiratory_rate": 18,
            "glucose_mg_dl": 96,
            "wbc_count": 8.1,
            "platelets_count": 240,
            "travel_exposure": 0,
            "contact_exposure": 1,
            "chronic_conditions_count": 0,
            "symptom_duration_days": 3,
            "weight_loss": 0,
            "neck_stiffness": 0,
            "photophobia": 0,
            "age": 34,
        },
    ),
    DiseaseProfile(
        code="common_cold",
        name="Common Cold",
        severity=DiseaseSeverity.LOW,
        specialty="Primary Care",
        description="Upper respiratory viral illness with mild symptoms and self-limited course.",
        triage_guidance="Conservative care is usually sufficient in the absence of red flags.",
        recommended_labs=("None routinely required",),
        recommended_specialists=("Primary Care",),
        lifestyle_advice=("Rest", "Fluids", "Over-the-counter symptom relief"),
        symptom_profile={
            "fever_celsius": 37.7,
            "cough_severity": 1,
            "sore_throat": 1,
            "shortness_of_breath": 0,
            "chest_pain": 0,
            "headache": 0,
            "fatigue": 1,
            "nausea": 0,
            "vomiting": 0,
            "diarrhea": 0,
            "abdominal_pain": 0,
            "rash": 0,
            "urinary_burning": 0,
            "joint_pain": 0,
            "loss_of_taste_smell": 0,
            "oxygen_saturation": 99,
            "systolic_bp": 118,
            "diastolic_bp": 76,
            "heart_rate": 82,
            "respiratory_rate": 16,
            "glucose_mg_dl": 92,
            "wbc_count": 6.2,
            "platelets_count": 250,
            "travel_exposure": 0,
            "contact_exposure": 1,
            "chronic_conditions_count": 0,
            "symptom_duration_days": 2,
            "weight_loss": 0,
            "neck_stiffness": 0,
            "photophobia": 0,
            "age": 28,
        },
    ),
    DiseaseProfile(
        code="pneumonia",
        name="Pneumonia",
        severity=DiseaseSeverity.HIGH,
        specialty="Pulmonology",
        description="Lower respiratory infection with cough, fever, and impaired oxygenation.",
        triage_guidance="Evaluate urgently when dyspnea, pleuritic chest pain, or low oxygen saturation is present.",
        recommended_labs=("Chest X-ray", "CBC", "Procalcitonin"),
        recommended_specialists=("Pulmonology", "Emergency Medicine"),
        lifestyle_advice=("Seek urgent evaluation if breathing worsens", "Hydrate", "Avoid exertion"),
        symptom_profile={
            "fever_celsius": 39.0,
            "cough_severity": 3,
            "sore_throat": 0,
            "shortness_of_breath": 1,
            "chest_pain": 1,
            "headache": 1,
            "fatigue": 2,
            "nausea": 0,
            "vomiting": 0,
            "diarrhea": 0,
            "abdominal_pain": 0,
            "rash": 0,
            "urinary_burning": 0,
            "joint_pain": 0,
            "loss_of_taste_smell": 0,
            "oxygen_saturation": 91,
            "systolic_bp": 116,
            "diastolic_bp": 74,
            "heart_rate": 106,
            "respiratory_rate": 26,
            "glucose_mg_dl": 100,
            "wbc_count": 13.8,
            "platelets_count": 220,
            "travel_exposure": 0,
            "contact_exposure": 0,
            "chronic_conditions_count": 1,
            "symptom_duration_days": 5,
            "weight_loss": 0,
            "neck_stiffness": 0,
            "photophobia": 0,
            "age": 67,
        },
    ),
    DiseaseProfile(
        code="covid19",
        name="COVID-19",
        severity=DiseaseSeverity.HIGH,
        specialty="Infectious Diseases",
        description="SARS-CoV-2 infection with respiratory or systemic manifestations.",
        triage_guidance="Escalate rapidly if oxygen saturation falls or chest pain and dyspnea are present.",
        recommended_labs=("SARS-CoV-2 PCR", "Pulse oximetry", "CBC"),
        recommended_specialists=("Infectious Diseases", "Pulmonology"),
        lifestyle_advice=("Isolate as clinically indicated", "Hydrate", "Monitor oxygen saturation"),
        symptom_profile={
            "fever_celsius": 38.3,
            "cough_severity": 2,
            "sore_throat": 1,
            "shortness_of_breath": 1,
            "chest_pain": 0,
            "headache": 1,
            "fatigue": 2,
            "nausea": 0,
            "vomiting": 0,
            "diarrhea": 1,
            "abdominal_pain": 0,
            "rash": 0,
            "urinary_burning": 0,
            "joint_pain": 1,
            "loss_of_taste_smell": 1,
            "oxygen_saturation": 93,
            "systolic_bp": 120,
            "diastolic_bp": 77,
            "heart_rate": 99,
            "respiratory_rate": 22,
            "glucose_mg_dl": 101,
            "wbc_count": 7.8,
            "platelets_count": 210,
            "travel_exposure": 1,
            "contact_exposure": 1,
            "chronic_conditions_count": 0,
            "symptom_duration_days": 4,
            "weight_loss": 0,
            "neck_stiffness": 0,
            "photophobia": 0,
            "age": 41,
        },
    ),
    DiseaseProfile(
        code="gastroenteritis",
        name="Acute Gastroenteritis",
        severity=DiseaseSeverity.MODERATE,
        specialty="Gastroenterology",
        description="Acute gastrointestinal infection causing diarrhea, vomiting, and dehydration risk.",
        triage_guidance="Hydration and electrolyte replacement are key; evaluate dehydration promptly.",
        recommended_labs=("BMP", "Stool PCR", "CBC"),
        recommended_specialists=("Gastroenterology", "Primary Care"),
        lifestyle_advice=("Oral rehydration", "Small frequent meals", "Avoid high-fat foods"),
        symptom_profile={
            "fever_celsius": 38.0,
            "cough_severity": 0,
            "sore_throat": 0,
            "shortness_of_breath": 0,
            "chest_pain": 0,
            "headache": 1,
            "fatigue": 2,
            "nausea": 1,
            "vomiting": 1,
            "diarrhea": 3,
            "abdominal_pain": 2,
            "rash": 0,
            "urinary_burning": 0,
            "joint_pain": 0,
            "loss_of_taste_smell": 0,
            "oxygen_saturation": 98,
            "systolic_bp": 112,
            "diastolic_bp": 72,
            "heart_rate": 102,
            "respiratory_rate": 18,
            "glucose_mg_dl": 95,
            "wbc_count": 10.5,
            "platelets_count": 245,
            "travel_exposure": 0,
            "contact_exposure": 1,
            "chronic_conditions_count": 0,
            "symptom_duration_days": 2,
            "weight_loss": 0,
            "neck_stiffness": 0,
            "photophobia": 0,
            "age": 24,
        },
    ),
    DiseaseProfile(
        code="dengue",
        name="Dengue Fever",
        severity=DiseaseSeverity.HIGH,
        specialty="Infectious Diseases",
        description="Mosquito-borne febrile illness with thrombocytopenia and myalgia.",
        triage_guidance="Urgent evaluation is appropriate when platelet counts fall or bleeding symptoms appear.",
        recommended_labs=("Dengue NS1", "CBC", "LFTs"),
        recommended_specialists=("Infectious Diseases", "Emergency Medicine"),
        lifestyle_advice=("Maintain hydration", "Avoid NSAIDs if possible", "Monitor for bleeding"),
        symptom_profile={
            "fever_celsius": 39.2,
            "cough_severity": 0,
            "sore_throat": 0,
            "shortness_of_breath": 0,
            "chest_pain": 0,
            "headache": 2,
            "fatigue": 2,
            "nausea": 1,
            "vomiting": 1,
            "diarrhea": 1,
            "abdominal_pain": 1,
            "rash": 1,
            "urinary_burning": 0,
            "joint_pain": 2,
            "loss_of_taste_smell": 0,
            "oxygen_saturation": 98,
            "systolic_bp": 110,
            "diastolic_bp": 70,
            "heart_rate": 98,
            "respiratory_rate": 18,
            "glucose_mg_dl": 94,
            "wbc_count": 4.8,
            "platelets_count": 125,
            "travel_exposure": 1,
            "contact_exposure": 0,
            "chronic_conditions_count": 0,
            "symptom_duration_days": 4,
            "weight_loss": 0,
            "neck_stiffness": 0,
            "photophobia": 0,
            "age": 29,
        },
    ),
    DiseaseProfile(
        code="urinary_tract_infection",
        name="Urinary Tract Infection",
        severity=DiseaseSeverity.MODERATE,
        specialty="Urology",
        description="Bacterial urinary infection producing dysuria, frequency, and systemic symptoms if advanced.",
        triage_guidance="Assess promptly when fever, flank pain, or nausea accompanies urinary symptoms.",
        recommended_labs=("Urinalysis", "Urine culture", "CBC"),
        recommended_specialists=("Urology", "Primary Care"),
        lifestyle_advice=("Hydrate", "Do not delay urination", "Complete prescribed antibiotics"),
        symptom_profile={
            "fever_celsius": 38.1,
            "cough_severity": 0,
            "sore_throat": 0,
            "shortness_of_breath": 0,
            "chest_pain": 0,
            "headache": 1,
            "fatigue": 1,
            "nausea": 1,
            "vomiting": 0,
            "diarrhea": 0,
            "abdominal_pain": 1,
            "rash": 0,
            "urinary_burning": 3,
            "joint_pain": 0,
            "loss_of_taste_smell": 0,
            "oxygen_saturation": 99,
            "systolic_bp": 118,
            "diastolic_bp": 75,
            "heart_rate": 88,
            "respiratory_rate": 16,
            "glucose_mg_dl": 98,
            "wbc_count": 11.0,
            "platelets_count": 260,
            "travel_exposure": 0,
            "contact_exposure": 0,
            "chronic_conditions_count": 1,
            "symptom_duration_days": 2,
            "weight_loss": 0,
            "neck_stiffness": 0,
            "photophobia": 0,
            "age": 45,
        },
    ),
    DiseaseProfile(
        code="migraine",
        name="Migraine",
        severity=DiseaseSeverity.MODERATE,
        specialty="Neurology",
        description="Primary headache disorder with unilateral pain, photophobia, and nausea.",
        triage_guidance="Rule out secondary neurologic red flags before diagnosing migraine.",
        recommended_labs=("Neurologic exam", "CT head if red flags", "CBC"),
        recommended_specialists=("Neurology", "Primary Care"),
        lifestyle_advice=("Hydrate", "Rest in a dark room", "Track triggers"),
        symptom_profile={
            "fever_celsius": 37.0,
            "cough_severity": 0,
            "sore_throat": 0,
            "shortness_of_breath": 0,
            "chest_pain": 0,
            "headache": 3,
            "fatigue": 1,
            "nausea": 1,
            "vomiting": 0,
            "diarrhea": 0,
            "abdominal_pain": 0,
            "rash": 0,
            "urinary_burning": 0,
            "joint_pain": 0,
            "loss_of_taste_smell": 0,
            "oxygen_saturation": 99,
            "systolic_bp": 122,
            "diastolic_bp": 80,
            "heart_rate": 80,
            "respiratory_rate": 16,
            "glucose_mg_dl": 91,
            "wbc_count": 6.0,
            "platelets_count": 245,
            "travel_exposure": 0,
            "contact_exposure": 0,
            "chronic_conditions_count": 0,
            "symptom_duration_days": 1,
            "weight_loss": 0,
            "neck_stiffness": 0,
            "photophobia": 1,
            "age": 31,
        },
    ),
    DiseaseProfile(
        code="hypertension",
        name="Hypertension",
        severity=DiseaseSeverity.MODERATE,
        specialty="Cardiology",
        description="Persistent elevation of blood pressure often detected incidentally or with complications.",
        triage_guidance="Urgent evaluation is needed for hypertensive emergency symptoms or severe elevation.",
        recommended_labs=("Ambulatory blood pressure monitoring", "BMP", "ECG"),
        recommended_specialists=("Cardiology", "Primary Care"),
        lifestyle_advice=("Reduce sodium intake", "Exercise regularly", "Follow prescribed therapy"),
        symptom_profile={
            "fever_celsius": 36.8,
            "cough_severity": 0,
            "sore_throat": 0,
            "shortness_of_breath": 0,
            "chest_pain": 0,
            "headache": 1,
            "fatigue": 1,
            "nausea": 0,
            "vomiting": 0,
            "diarrhea": 0,
            "abdominal_pain": 0,
            "rash": 0,
            "urinary_burning": 0,
            "joint_pain": 0,
            "loss_of_taste_smell": 0,
            "oxygen_saturation": 99,
            "systolic_bp": 156,
            "diastolic_bp": 96,
            "heart_rate": 84,
            "respiratory_rate": 16,
            "glucose_mg_dl": 97,
            "wbc_count": 6.7,
            "platelets_count": 250,
            "travel_exposure": 0,
            "contact_exposure": 0,
            "chronic_conditions_count": 2,
            "symptom_duration_days": 14,
            "weight_loss": 0,
            "neck_stiffness": 0,
            "photophobia": 0,
            "age": 59,
        },
    ),
    DiseaseProfile(
        code="diabetes_mellitus",
        name="Diabetes Mellitus",
        severity=DiseaseSeverity.MODERATE,
        specialty="Endocrinology",
        description="Metabolic disease characterized by hyperglycemia and systemic complications.",
        triage_guidance="Hyperglycemia with dehydration or altered mental status needs urgent evaluation.",
        recommended_labs=("HbA1c", "Fasting glucose", "Urinalysis"),
        recommended_specialists=("Endocrinology", "Primary Care"),
        lifestyle_advice=("Monitor carbohydrate intake", "Exercise consistently", "Check glucose regularly"),
        symptom_profile={
            "fever_celsius": 36.9,
            "cough_severity": 0,
            "sore_throat": 0,
            "shortness_of_breath": 0,
            "chest_pain": 0,
            "headache": 1,
            "fatigue": 2,
            "nausea": 0,
            "vomiting": 0,
            "diarrhea": 0,
            "abdominal_pain": 0,
            "rash": 0,
            "urinary_burning": 0,
            "joint_pain": 0,
            "loss_of_taste_smell": 0,
            "oxygen_saturation": 99,
            "systolic_bp": 132,
            "diastolic_bp": 84,
            "heart_rate": 86,
            "respiratory_rate": 16,
            "glucose_mg_dl": 214,
            "wbc_count": 7.0,
            "platelets_count": 248,
            "travel_exposure": 0,
            "contact_exposure": 0,
            "chronic_conditions_count": 2,
            "symptom_duration_days": 21,
            "weight_loss": 1,
            "neck_stiffness": 0,
            "photophobia": 0,
            "age": 52,
        },
    ),
    DiseaseProfile(
        code="dermatitis",
        name="Dermatitis",
        severity=DiseaseSeverity.LOW,
        specialty="Dermatology",
        description="Inflammatory skin condition with erythema, rash, and pruritus.",
        triage_guidance="Topical management is typical unless infection or systemic symptoms are present.",
        recommended_labs=("Dermatology exam", "Allergy review", "Skin scraping if indicated"),
        recommended_specialists=("Dermatology", "Primary Care"),
        lifestyle_advice=("Avoid triggers", "Use gentle emollients", "Keep skin moisturized"),
        symptom_profile={
            "fever_celsius": 36.7,
            "cough_severity": 0,
            "sore_throat": 0,
            "shortness_of_breath": 0,
            "chest_pain": 0,
            "headache": 0,
            "fatigue": 0,
            "nausea": 0,
            "vomiting": 0,
            "diarrhea": 0,
            "abdominal_pain": 0,
            "rash": 3,
            "urinary_burning": 0,
            "joint_pain": 0,
            "loss_of_taste_smell": 0,
            "oxygen_saturation": 99,
            "systolic_bp": 116,
            "diastolic_bp": 74,
            "heart_rate": 76,
            "respiratory_rate": 16,
            "glucose_mg_dl": 90,
            "wbc_count": 6.1,
            "platelets_count": 255,
            "travel_exposure": 0,
            "contact_exposure": 0,
            "chronic_conditions_count": 0,
            "symptom_duration_days": 7,
            "weight_loss": 0,
            "neck_stiffness": 0,
            "photophobia": 0,
            "age": 27,
        },
    ),
    DiseaseProfile(
        code="malaria",
        name="Malaria",
        severity=DiseaseSeverity.HIGH,
        specialty="Infectious Diseases",
        description="Parasitic infection associated with cyclic fever, systemic symptoms, and travel exposure.",
        triage_guidance="Urgent evaluation is warranted for febrile travelers with thrombocytopenia or altered mental state.",
        recommended_labs=("Malaria smear", "Rapid antigen test", "CBC"),
        recommended_specialists=("Infectious Diseases", "Emergency Medicine"),
        lifestyle_advice=("Seek urgent treatment", "Hydrate", "Avoid travel until evaluated"),
        symptom_profile={
            "fever_celsius": 39.1,
            "cough_severity": 0,
            "sore_throat": 0,
            "shortness_of_breath": 0,
            "chest_pain": 0,
            "headache": 2,
            "fatigue": 2,
            "nausea": 1,
            "vomiting": 1,
            "diarrhea": 0,
            "abdominal_pain": 1,
            "rash": 0,
            "urinary_burning": 0,
            "joint_pain": 1,
            "loss_of_taste_smell": 0,
            "oxygen_saturation": 98,
            "systolic_bp": 108,
            "diastolic_bp": 68,
            "heart_rate": 104,
            "respiratory_rate": 20,
            "glucose_mg_dl": 93,
            "wbc_count": 5.2,
            "platelets_count": 145,
            "travel_exposure": 1,
            "contact_exposure": 0,
            "chronic_conditions_count": 0,
            "symptom_duration_days": 4,
            "weight_loss": 0,
            "neck_stiffness": 0,
            "photophobia": 0,
            "age": 36,
        },
    ),
)


DISEASE_PROFILE_BY_CODE = {profile.code: profile for profile in DISEASE_PROFILES}